stages:
  data_ingestion:
    cmd: python src\pipeline\data_ingestion_pipline.py
    deps:
      - src\pipeline\data_ingestion_pipline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data


  base_model:
    cmd: python src\pipeline\base_model_pipline.py
    deps:
      - src\pipeline\base_model_pipline.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/base_model


  model_train:
    cmd: python src\pipeline\model_train_pipeline.py
    deps:
      - src\pipeline\model_train_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - model\model.h5


  evaluation:
    cmd: python src\pipeline\model_eval_pipline.py
    deps:
      - src\pipeline\model_eval_pipline.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - model\model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false