artifacts_root: artifacts

data_ingestion:
  dir: artifacts/data_ingestion 
  source_url: https://drive.google.com/file/d/1ZrFE6RSlNerUfwexpGlhc2r3haiV-CIz/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion